<?php

namespace EK\MailBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BounceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BounceRepository extends EntityRepository
{
}
