<?php

namespace EK\MailBundle\Repository;

/**
 * GlobalTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalTestRepository extends \Doctrine\ORM\EntityRepository
{
}
